// <auto-generated />
using System;
using FarmAppAspire.CustomerService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FarmAppAspire.CustomerService.Migrations
{
    [DbContext(typeof(CustomerDbContext))]
    partial class CustomerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FarmAppAspire.CustomerService.Models.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("BillingUsesShipping")
                        .HasColumnType("boolean");

                    b.Property<string>("ChannelType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerKey")
                        .HasColumnType("text");

                    b.Property<bool>("CustomerKeyCollision")
                        .HasColumnType("boolean");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("PaymentTerms")
                        .HasColumnType("text");

                    b.Property<string>("PrimaryEmail")
                        .HasColumnType("text");

                    b.Property<string>("PrimaryPhone")
                        .HasColumnType("text");

                    b.Property<string>("TaxId")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("FarmAppAspire.CustomerService.Models.CustomerAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Line1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Line2")
                        .HasColumnType("text");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustomerAddresses");
                });

            modelBuilder.Entity("FarmAppAspire.CustomerService.Models.CustomerContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Mobile")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustomerContacts");
                });

            modelBuilder.Entity("FarmAppAspire.CustomerService.Models.CustomerPricing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BoxSize")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<int>("MinQty")
                        .HasColumnType("integer");

                    b.Property<decimal>("PricePerLb")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ShippingRate")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId", "BoxSize")
                        .IsUnique();

                    b.ToTable("CustomerPricings");
                });

            modelBuilder.Entity("FarmAppAspire.CustomerService.Models.FedExTierConfig", b =>
                {
                    b.Property<string>("TierSize")
                        .HasColumnType("text");

                    b.Property<decimal>("FixedPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("WeightOz")
                        .HasColumnType("numeric");

                    b.HasKey("TierSize");

                    b.ToTable("FedExTierConfigs");

                    b.HasData(
                        new
                        {
                            TierSize = "OneOz",
                            FixedPrice = 5.99m,
                            WeightOz = 1m
                        },
                        new
                        {
                            TierSize = "TwoOz",
                            FixedPrice = 8.99m,
                            WeightOz = 2m
                        },
                        new
                        {
                            TierSize = "FourOz",
                            FixedPrice = 12.99m,
                            WeightOz = 4m
                        },
                        new
                        {
                            TierSize = "EightOz",
                            FixedPrice = 19.99m,
                            WeightOz = 8m
                        },
                        new
                        {
                            TierSize = "OneLb",
                            FixedPrice = 27.99m,
                            WeightOz = 16m
                        },
                        new
                        {
                            TierSize = "TwoLb",
                            FixedPrice = 42.99m,
                            WeightOz = 32m
                        },
                        new
                        {
                            TierSize = "ThreeLb",
                            FixedPrice = 68.99m,
                            WeightOz = 48m
                        },
                        new
                        {
                            TierSize = "FiveLb",
                            FixedPrice = 99.99m,
                            WeightOz = 80m
                        });
                });

            modelBuilder.Entity("FarmAppAspire.CustomerService.Models.InsulatedBoxConfig", b =>
                {
                    b.Property<string>("Size")
                        .HasColumnType("text");

                    b.Property<decimal>("BasePricePerLb")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<decimal>("WeightLbs")
                        .HasColumnType("numeric");

                    b.HasKey("Size");

                    b.ToTable("InsulatedBoxConfigs");

                    b.HasData(
                        new
                        {
                            Size = "FiveLb",
                            BasePricePerLb = 13m,
                            IsDefault = false,
                            WeightLbs = 5m
                        },
                        new
                        {
                            Size = "TenLb",
                            BasePricePerLb = 13m,
                            IsDefault = false,
                            WeightLbs = 10m
                        },
                        new
                        {
                            Size = "TwelveLb",
                            BasePricePerLb = 13m,
                            IsDefault = true,
                            WeightLbs = 12m
                        });
                });

            modelBuilder.Entity("FarmAppAspire.CustomerService.Models.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OrderInstanceId")
                        .HasColumnType("uuid");

                    b.Property<int>("SeasonYear")
                        .HasColumnType("integer");

                    b.Property<int>("SeekNum")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Label")
                        .IsUnique();

                    b.HasIndex("OrderInstanceId")
                        .IsUnique();

                    b.HasIndex("CustomerId", "SeasonYear", "Channel", "SeekNum")
                        .IsUnique();

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("FarmAppAspire.CustomerService.Models.OrderInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ContactId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsSample")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ShipDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("StandingOrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("WeekOf")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.HasIndex("StandingOrderId");

                    b.HasIndex("CustomerId", "WeekOf", "Status");

                    b.ToTable("OrderInstances");
                });

            modelBuilder.Entity("FarmAppAspire.CustomerService.Models.OrderInstanceLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BoxSize")
                        .HasColumnType("text");

                    b.Property<decimal?>("EffectivePricePerLb")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("FedExFixedPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("FedExTierSize")
                        .HasColumnType("text");

                    b.Property<Guid>("OrderInstanceId")
                        .HasColumnType("uuid");

                    b.Property<string>("PackagingType")
                        .HasColumnType("text");

                    b.Property<int>("Qty")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderInstanceId");

                    b.ToTable("OrderInstanceLines");
                });

            modelBuilder.Entity("FarmAppAspire.CustomerService.Models.StandingOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ContactId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsSample")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("MonthlyWeek")
                        .HasColumnType("text");

                    b.Property<int>("SeasonYear")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartWeek")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.HasIndex("CustomerId", "Status");

                    b.ToTable("StandingOrders");
                });

            modelBuilder.Entity("FarmAppAspire.CustomerService.Models.StandingOrderLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BoxSize")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Qty")
                        .HasColumnType("integer");

                    b.Property<Guid>("StandingOrderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StandingOrderId");

                    b.ToTable("StandingOrderLines");
                });

            modelBuilder.Entity("FarmAppAspire.CustomerService.Models.StandingOrderSkip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("StandingOrderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("WeekOf")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StandingOrderId", "WeekOf")
                        .IsUnique();

                    b.ToTable("StandingOrderSkips");
                });

            modelBuilder.Entity("FarmAppAspire.CustomerService.Models.CustomerAddress", b =>
                {
                    b.HasOne("FarmAppAspire.CustomerService.Models.Customer", "Customer")
                        .WithMany("Addresses")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("FarmAppAspire.CustomerService.Models.CustomerContact", b =>
                {
                    b.HasOne("FarmAppAspire.CustomerService.Models.Customer", "Customer")
                        .WithMany("Contacts")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("FarmAppAspire.CustomerService.Models.CustomerPricing", b =>
                {
                    b.HasOne("FarmAppAspire.CustomerService.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("FarmAppAspire.CustomerService.Models.Invoice", b =>
                {
                    b.HasOne("FarmAppAspire.CustomerService.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmAppAspire.CustomerService.Models.OrderInstance", "OrderInstance")
                        .WithOne("Invoice")
                        .HasForeignKey("FarmAppAspire.CustomerService.Models.Invoice", "OrderInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("OrderInstance");
                });

            modelBuilder.Entity("FarmAppAspire.CustomerService.Models.OrderInstance", b =>
                {
                    b.HasOne("FarmAppAspire.CustomerService.Models.CustomerContact", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactId");

                    b.HasOne("FarmAppAspire.CustomerService.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmAppAspire.CustomerService.Models.StandingOrder", "StandingOrder")
                        .WithMany("Instances")
                        .HasForeignKey("StandingOrderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Contact");

                    b.Navigation("Customer");

                    b.Navigation("StandingOrder");
                });

            modelBuilder.Entity("FarmAppAspire.CustomerService.Models.OrderInstanceLine", b =>
                {
                    b.HasOne("FarmAppAspire.CustomerService.Models.OrderInstance", "OrderInstance")
                        .WithMany("Lines")
                        .HasForeignKey("OrderInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderInstance");
                });

            modelBuilder.Entity("FarmAppAspire.CustomerService.Models.StandingOrder", b =>
                {
                    b.HasOne("FarmAppAspire.CustomerService.Models.CustomerContact", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactId");

                    b.HasOne("FarmAppAspire.CustomerService.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("FarmAppAspire.CustomerService.Models.StandingOrderLine", b =>
                {
                    b.HasOne("FarmAppAspire.CustomerService.Models.StandingOrder", "StandingOrder")
                        .WithMany("Lines")
                        .HasForeignKey("StandingOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StandingOrder");
                });

            modelBuilder.Entity("FarmAppAspire.CustomerService.Models.StandingOrderSkip", b =>
                {
                    b.HasOne("FarmAppAspire.CustomerService.Models.StandingOrder", "StandingOrder")
                        .WithMany("Skips")
                        .HasForeignKey("StandingOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StandingOrder");
                });

            modelBuilder.Entity("FarmAppAspire.CustomerService.Models.Customer", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Contacts");
                });

            modelBuilder.Entity("FarmAppAspire.CustomerService.Models.OrderInstance", b =>
                {
                    b.Navigation("Invoice");

                    b.Navigation("Lines");
                });

            modelBuilder.Entity("FarmAppAspire.CustomerService.Models.StandingOrder", b =>
                {
                    b.Navigation("Instances");

                    b.Navigation("Lines");

                    b.Navigation("Skips");
                });
#pragma warning restore 612, 618
        }
    }
}
